# Generated by Django 3.2 on 2021-04-20 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.FloatField()),
                ('store_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=5)),
                ('start_hour', models.PositiveSmallIntegerField(null=True)),
                ('start_min', models.PositiveSmallIntegerField(null=True)),
                ('end_hour', models.PositiveSmallIntegerField(null=True)),
                ('end_min', models.PositiveSmallIntegerField(null=True)),
                ('books_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore_api.bookstore')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('books_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore_api.bookstore')),
            ],
        ),
    ]
