# Generated by Django 3.2 on 2021-04-16 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=20)),
                ('start_min', models.TimeField()),
                ('end_min', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.FloatField()),
                ('store_name', models.CharField(max_length=100)),
                ('opening_hours', models.ManyToManyField(to='bookstore_api.OpeningHours')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore_api.bookstore')),
            ],
        ),
    ]
