# Generated by Django 3.2 on 2021-04-16 01:46
import os
from django.db import migrations
from django.core import serializers

book_store_json_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../data'))
book_store_filename = 'book_store_data.json'

def load_book_store(apps, schema_editor):
    book_store_file = os.path.join(book_store_json_dir, book_store_filename)

    book_store = open(book_store_file, 'rb')
    objects = serializers.deserialize('json', book_store, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    book_store.close()

def unload_book_store(apps, schema_editor):
    book_store_model = apps.get_model("bookstore_api", "model")
    book_store_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(load_book_store, reverse_code=unload_book_store),
    ]
