# Generated by Django 3.2 on 2021-04-20 03:41

import os
import json

from django.db import migrations

book_store_json_dir = os.path.abspath(
    os.path.join(os.path.dirname(__file__), '../../data'))
book_store_filename = 'example.json'


def parse_op_hour(op_h_data):
    week_day, start_hour, start_min, end_hour, end_min = op_h_data['week_day'],\
        op_h_data['start_hour'], op_h_data['start_min'], op_h_data['end_hour'], op_h_data['end_min']

    return {
        'week_day': week_day,
        'start_hour': start_hour,
        'start_min': start_min,
        'end_hour': end_hour,
        'end_min': end_min,
    }


def load_book_store(apps, schema_editor):
    book_store_file = os.path.join(book_store_json_dir, book_store_filename)

    with open(book_store_file, 'r') as book_store:
        data = json.load(book_store)

        BookStore = apps.get_model("bookstore_api", "BookStore")
        Book = apps.get_model("bookstore_api", "Book")
        OpeningHour = apps.get_model("bookstore_api", "OpeningHour")

        for store_data in data:
            bs = BookStore(
                cash_balance=store_data['cashBalance'],
                store_name=store_data['storeName'],
            )
            bs.save()

            for book_data in store_data['book']:
                Book(
                    books_store=bs,
                    book_name=book_data['bookName'],
                    price=book_data['price'],
                ).save()

            for op_h_data in store_data['openingHour']:
                open_time_dict = parse_op_hour(op_h_data)

                OpeningHour(
                    books_store=bs,
                    week_day=open_time_dict['week_day'],
                    start_hour=open_time_dict['start_hour'],
                    start_min=open_time_dict['start_min'],
                    end_hour=open_time_dict['end_hour'],
                    end_min=open_time_dict['end_min']
                ).save()


def unload_book_store(apps, schema_editor):
    BookStore = apps.get_model("bookstore_api", "BookStore")
    Book = apps.get_model("bookstore_api", "Book")
    OpeningHour = apps.get_model("bookstore_api", "OpeningHour")

    for mod in [BookStore, Book, OpeningHour]:
        mod.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_book_store, reverse_code=unload_book_store),
    ]
