# Generated by Django 3.2 on 2021-04-20 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0003_prepare_bookstore_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cash_balance', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='books_store',
            new_name='book_store',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bookstore',
            old_name='store_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='openinghour',
            old_name='books_store',
            new_name='book_store',
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('store_name', models.CharField(max_length=100)),
                ('transaction_amount', models.FloatField()),
                ('transaction_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore_api.user')),
            ],
        ),
    ]
