# Generated by Django 3.2 on 2021-05-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0005_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasehistory', to='bookstore_api.user'),
        ),
    ]
