# Generated by Django 3.2 on 2021-05-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0006_alter_purchasehistory_transaction_date'),
        ('bookstore_api', '0006_auto_20210522_2352'),
    ]

    operations = [
    ]
